name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Install Python Dependencies (Buildozer & Cython)
        run: |
          # Cython ka purana version lagana zaroori hai Kivy ke liye, nahi toh error aayega
          pip3 install --user --upgrade buildozer "cython<3.0.0" virtualenv

      - name: Build APK (Isme 10-15 minute lag sakte hain)
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer android debug

      - name: Upload APK File
        uses: actions/upload-artifact@v3
        with:
          name: StudyLike_PRO_APK
          path: bin/*.apk
