name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer Action
        # Ye action sabse stable hai aur API levels khud handle karta hai
        uses: digiampifa/buildozer-action@v2
        with:
          buildozer_version: stable
          python_version: 3.11
          # Ye command licenses ko accept karega aur API 33 ko handle karega
          command: buildozer android debug
